reservoir.res: written by SWAT+ editor v2.1.0 on 2026-01-19 18:46 for SWAT+ rev.2.1.4
      id  name                          init               hyd               rel               sed               nut  
       1  res001                    initres1            res001              null           sedres1           nutres1  
       2  res002                    initres1            res002              null           sedres1           nutres1  
       3  res003                    initres1            res003              null           sedres1           nutres1  
       4  res004                    initres1            res004              null           sedres1           nutres1  
       5  res005                    initres1            res005              null           sedres1           nutres1  
       6  res006                    initres1            res006              null           sedres1           nutres1  
       7  res007                    initres1            res007     drawdown_days           sedres1           nutres1  
       8  res008                    initres1            res008              null           sedres1           nutres1  
       9  res009                    initres1            res009              null           sedres1           nutres1  
      10  res010                    initres1            res010              null           sedres1           nutres1  
      11  res011                    initres1            res011              null           sedres1           nutres1  
      12  res012                    initres1            res012              null           sedres1           nutres1  
      13  res013                    initres1            res013              null           sedres1           nutres1  
      14  res014                    initres1            res014              null           sedres1           nutres1  
      15  res015                    initres1            res015              null           sedres1           nutres1  
      16  res016                    initres1            res016     drawdown_days           sedres1           nutres1  
      17  res017                    initres1            res017              null           sedres1           nutres1  
      18  res018                    initres1            res018              null           sedres1           nutres1  
      19  res019                    initres1            res019              null           sedres1           nutres1  
      20  res020                    initres1            res020              null           sedres1           nutres1  
      21  res021                    initres1            res021              null           sedres1           nutres1  
      22  res022                    initres1            res022              null           sedres1           nutres1  
      23  res023                    initres1            res023     drawdown_days           sedres1           nutres1  
      24  res024                    initres1            res024              null           sedres1           nutres1  
      25  res025                    initres1            res025              null           sedres1           nutres1  
      26  res026                    initres1            res026     drawdown_days           sedres1           nutres1  
      27  res027                    initres1            res027              null           sedres1           nutres1  
      28  res028                    initres1            res028              null           sedres1           nutres1  
      29  res029                    initres1            res029              null           sedres1           nutres1  
      30  res030                    initres1            res030              null           sedres1           nutres1  
      31  res031                    initres1            res031     drawdown_days           sedres1           nutres1  
      32  res032                    initres1            res032              null           sedres1           nutres1  
      33  res033                    initres1            res033              null           sedres1           nutres1  
      34  res034                    initres1            res034              null           sedres1           nutres1  
      35  res035                    initres1            res035              null           sedres1           nutres1  
      36  res036                    initres1            res036              null           sedres1           nutres1  
      37  res037                    initres1            res037              null           sedres1           nutres1  
      38  res038                    initres1            res038              null           sedres1           nutres1  
      39  res039                    initres1            res039              null           sedres1           nutres1  
      40  res040                    initres1            res040              null           sedres1           nutres1  
      41  res041                    initres1            res041              null           sedres1           nutres1  
      42  res042                    initres1            res042              null           sedres1           nutres1  
      43  res043                    initres1            res043     drawdown_days           sedres1           nutres1  
      44  res044                    initres1            res044              null           sedres1           nutres1  
      45  res045                    initres1            res045              null           sedres1           nutres1  
      46  res046                    initres1            res046              null           sedres1           nutres1  
      47  res047                    initres1            res047              null           sedres1           nutres1  
      48  res048                    initres1            res048              null           sedres1           nutres1  
      49  res049                    initres1            res049              null           sedres1           nutres1  
      50  res050                    initres1            res050              null           sedres1           nutres1  
      51  res051                    initres1            res051              null           sedres1           nutres1  
      52  res052                    initres1            res052              null           sedres1           nutres1  
      53  res053                    initres1            res053              null           sedres1           nutres1  
      54  res054                    initres1            res054     drawdown_days           sedres1           nutres1  
      55  res055                    initres1            res055              null           sedres1           nutres1  
      56  res056                    initres1            res056              null           sedres1           nutres1  
      57  res057                    initres1            res057     drawdown_days           sedres1           nutres1  
      58  res058                    initres1            res058              null           sedres1           nutres1  
      59  res059                    initres1            res059              null           sedres1           nutres1  
      60  res060                    initres1            res060              null           sedres1           nutres1  
      61  res061                    initres1            res061              null           sedres1           nutres1  
      62  res062                    initres1            res062              null           sedres1           nutres1  
      63  res063                    initres1            res063              null           sedres1           nutres1  
      64  res064                    initres1            res064     drawdown_days           sedres1           nutres1  
      65  res065                    initres1            res065              null           sedres1           nutres1  
      66  res066                    initres1            res066              null           sedres1           nutres1  
      67  res067                    initres1            res067              null           sedres1           nutres1  
      68  res068                    initres1            res068              null           sedres1           nutres1  
      69  res069                    initres1            res069              null           sedres1           nutres1  
      70  res070                    initres1            res070              null           sedres1           nutres1  
      71  res071                    initres1            res071              null           sedres1           nutres1  
      72  res072                    initres1            res072              null           sedres1           nutres1  
      73  res073                    initres1            res073              null           sedres1           nutres1  
      74  res074                    initres1            res074              null           sedres1           nutres1  
      75  res075                    initres1            res075              null           sedres1           nutres1  
      76  res076                    initres1            res076              null           sedres1           nutres1  
      77  res077                    initres1            res077              null           sedres1           nutres1  
      78  res078                    initres1            res078     drawdown_days           sedres1           nutres1  
      79  res079                    initres1            res079              null           sedres1           nutres1  
      80  res080                    initres1            res080              null           sedres1           nutres1  
      81  res081                    initres1            res081              null           sedres1           nutres1  
      82  res082                    initres1            res082              null           sedres1           nutres1  
      83  res083                    initres1            res083              null           sedres1           nutres1  
      84  res084                    initres1            res084              null           sedres1           nutres1  
      85  res085                    initres1            res085     drawdown_days           sedres1           nutres1  
      86  res086                    initres1            res086              null           sedres1           nutres1  
      87  res087                    initres1            res087              null           sedres1           nutres1  
      88  res088                    initres1            res088              null           sedres1           nutres1  
      89  res089                    initres1            res089              null           sedres1           nutres1  
      90  res090                    initres1            res090              null           sedres1           nutres1  
      91  res091                    initres1            res091              null           sedres1           nutres1  
      92  res092                    initres1            res092              null           sedres1           nutres1  
      93  res093                    initres1            res093              null           sedres1           nutres1  
      94  res094                    initres1            res094              null           sedres1           nutres1  
      95  res095                    initres1            res095              null           sedres1           nutres1  
      96  res096                    initres1            res096              null           sedres1           nutres1  
      97  res097                    initres1            res097              null           sedres1           nutres1  
      98  res098                    initres1            res098              null           sedres1           nutres1  
      99  res099                    initres1            res099              null           sedres1           nutres1  
     100  res100                    initres1            res100              null           sedres1           nutres1  
     101  res101                    initres1            res101              null           sedres1           nutres1  
     102  res102                    initres1            res102              null           sedres1           nutres1  
     103  res103                    initres1            res103              null           sedres1           nutres1  
     104  res104                    initres1            res104              null           sedres1           nutres1  
     105  res105                    initres1            res105              null           sedres1           nutres1  
     106  res106                    initres1            res106              null           sedres1           nutres1  
     107  res107                    initres1            res107              null           sedres1           nutres1  
     108  res108                    initres1            res108              null           sedres1           nutres1  
     109  res109                    initres1            res109              null           sedres1           nutres1  
     110  res110                    initres1            res110              null           sedres1           nutres1  
     111  res111                    initres1            res111              null           sedres1           nutres1  
     112  res112                    initres1            res112              null           sedres1           nutres1  
     113  res113                    initres1            res113              null           sedres1           nutres1  
     114  res114                    initres1            res114              null           sedres1           nutres1  
     115  res115                    initres1            res115              null           sedres1           nutres1  
     116  res116                    initres1            res116              null           sedres1           nutres1  
     117  res117                    initres1            res117              null           sedres1           nutres1  
     118  res118                    initres1            res118              null           sedres1           nutres1  
     119  res119                    initres1            res119              null           sedres1           nutres1  
     120  res120                    initres1            res120              null           sedres1           nutres1  
     121  res121                    initres1            res121              null           sedres1           nutres1  
     122  res122                    initres1            res122              null           sedres1           nutres1  
     123  res123                    initres1            res123              null           sedres1           nutres1  
     124  res124                    initres1            res124              null           sedres1           nutres1  
     125  res125                    initres1            res125              null           sedres1           nutres1  
     126  res126                    initres1            res126              null           sedres1           nutres1  
     127  res127                    initres1            res127              null           sedres1           nutres1  
     128  res128                    initres1            res128              null           sedres1           nutres1  
     129  res129                    initres1            res129              null           sedres1           nutres1  
     130  res130                    initres1            res130              null           sedres1           nutres1  
     131  res131                    initres1            res131              null           sedres1           nutres1  
     132  res132                    initres1            res132     drawdown_days           sedres1           nutres1  
     133  res133                    initres1            res133     drawdown_days           sedres1           nutres1  
     134  res134                    initres1            res134              null           sedres1           nutres1  
     135  res135                    initres1            res135              null           sedres1           nutres1  
     136  res136                    initres1            res136              null           sedres1           nutres1  
     137  res137                    initres1            res137              null           sedres1           nutres1  
     138  res138                    initres1            res138     drawdown_days           sedres1           nutres1  
     139  res139                    initres1            res139              null           sedres1           nutres1  
     140  res140                    initres1            res140     drawdown_days           sedres1           nutres1  
     141  res141                    initres1            res141              null           sedres1           nutres1  
     142  res142                    initres1            res142              null           sedres1           nutres1  
     143  res143                    initres1            res143              null           sedres1           nutres1  
     144  res144                    initres1            res144              null           sedres1           nutres1  
     145  res145                    initres1            res145              null           sedres1           nutres1  
     146  res146                    initres1            res146              null           sedres1           nutres1  
     147  res147                    initres1            res147     drawdown_days           sedres1           nutres1  
     148  res148                    initres1            res148     drawdown_days           sedres1           nutres1  
     149  res149                    initres1            res149     drawdown_days           sedres1           nutres1  
     150  res150                    initres1            res150     drawdown_days           sedres1           nutres1  
     151  res151                    initres1            res151              null           sedres1           nutres1  
     152  res152                    initres1            res152              null           sedres1           nutres1  
     153  res153                    initres1            res153     drawdown_days           sedres1           nutres1  
     154  res154                    initres1            res154     drawdown_days           sedres1           nutres1  
     155  res155                    initres1            res155              null           sedres1           nutres1  
     156  res156                    initres1            res156              null           sedres1           nutres1  
     157  res157                    initres1            res157              null           sedres1           nutres1  
     158  res158                    initres1            res158              null           sedres1           nutres1  
     159  res159                    initres1            res159              null           sedres1           nutres1  
     160  res160                    initres1            res160              null           sedres1           nutres1  
     161  res161                    initres1            res161              null           sedres1           nutres1  
     162  res162                    initres1            res162              null           sedres1           nutres1  
     163  res163                    initres1            res163              null           sedres1           nutres1  
     164  res164                    initres1            res164              null           sedres1           nutres1  
     165  res165                    initres1            res165              null           sedres1           nutres1  
     166  res166                    initres1            res166              null           sedres1           nutres1  
     167  res167                    initres1            res167              null           sedres1           nutres1  
     168  res168                    initres1            res168              null           sedres1           nutres1  
     169  res169                    initres1            res169              null           sedres1           nutres1  
     170  res170                    initres1            res170              null           sedres1           nutres1  
     171  res171                    initres1            res171              null           sedres1           nutres1  
     172  res172                    initres1            res172              null           sedres1           nutres1  
     173  res173                    initres1            res173              null           sedres1           nutres1  
     174  res174                    initres1            res174              null           sedres1           nutres1  
     175  res175                    initres1            res175     drawdown_days           sedres1           nutres1  
     176  res176                    initres1            res176              null           sedres1           nutres1  
     177  res177                    initres1            res177     drawdown_days           sedres1           nutres1  
     178  res178                    initres1            res178              null           sedres1           nutres1  
     179  res179                    initres1            res179              null           sedres1           nutres1  
     180  res180                    initres1            res180              null           sedres1           nutres1  
     181  res181                    initres1            res181              null           sedres1           nutres1  
     182  res182                    initres1            res182              null           sedres1           nutres1  
     183  res183                    initres1            res183              null           sedres1           nutres1  
     184  res184                    initres1            res184              null           sedres1           nutres1  
     185  res185                    initres1            res185              null           sedres1           nutres1  
     186  res186                    initres1            res186              null           sedres1           nutres1  
     187  res187                    initres1            res187              null           sedres1           nutres1  
     188  res188                    initres1            res188              null           sedres1           nutres1  
     189  res189                    initres1            res189              null           sedres1           nutres1  
     190  res190                    initres1            res190              null           sedres1           nutres1  
     191  res191                    initres1            res191              null           sedres1           nutres1  
     192  res192                    initres1            res192              null           sedres1           nutres1  
     193  res193                    initres1            res193              null           sedres1           nutres1  
     194  res194                    initres1            res194              null           sedres1           nutres1  
     195  res195                    initres1            res195              null           sedres1           nutres1  
     196  res196                    initres1            res196              null           sedres1           nutres1  
     197  res197                    initres1            res197              null           sedres1           nutres1  
     198  res198                    initres1            res198              null           sedres1           nutres1  
     199  res199                    initres1            res199              null           sedres1           nutres1  
     200  res200                    initres1            res200     drawdown_days           sedres1           nutres1  
     201  res201                    initres1            res201              null           sedres1           nutres1  
     202  res202                    initres1            res202              null           sedres1           nutres1  
     203  res203                    initres1            res203              null           sedres1           nutres1  
     204  res204                    initres1            res204              null           sedres1           nutres1  
     205  res205                    initres1            res205              null           sedres1           nutres1  
     206  res206                    initres1            res206              null           sedres1           nutres1  
     207  res207                    initres1            res207              null           sedres1           nutres1  
     208  res208                    initres1            res208              null           sedres1           nutres1  
     209  res209                    initres1            res209              null           sedres1           nutres1  
     210  res210                    initres1            res210     drawdown_days           sedres1           nutres1  
     211  res211                    initres1            res211              null           sedres1           nutres1  
     212  res212                    initres1            res212              null           sedres1           nutres1  
     213  res213                    initres1            res213              null           sedres1           nutres1  
     214  res214                    initres1            res214              null           sedres1           nutres1  
     215  res215                    initres1            res215              null           sedres1           nutres1  
     216  res216                    initres1            res216              null           sedres1           nutres1  
     217  res217                    initres1            res217              null           sedres1           nutres1  
     218  res218                    initres1            res218              null           sedres1           nutres1  
     219  res219                    initres1            res219              null           sedres1           nutres1  
     220  res220                    initres1            res220              null           sedres1           nutres1  
     221  res221                    initres1            res221              null           sedres1           nutres1  
     222  res222                    initres1            res222     drawdown_days           sedres1           nutres1  
     223  res223                    initres1            res223     drawdown_days           sedres1           nutres1  
     224  res224                    initres1            res224     drawdown_days           sedres1           nutres1  
     225  res225                    initres1            res225              null           sedres1           nutres1  
     226  res226                    initres1            res226              null           sedres1           nutres1  
     227  res227                    initres1            res227              null           sedres1           nutres1  
     228  res228                    initres1            res228     drawdown_days           sedres1           nutres1  
     229  res229                    initres1            res229              null           sedres1           nutres1  
     230  res230                    initres1            res230              null           sedres1           nutres1  
     231  res231                    initres1            res231              null           sedres1           nutres1  
     232  res232                    initres1            res232     drawdown_days           sedres1           nutres1  
     233  res233                    initres1            res233              null           sedres1           nutres1  
     234  res234                    initres1            res234     drawdown_days           sedres1           nutres1  
     235  res235                    initres1            res235              null           sedres1           nutres1  
     236  res236                    initres1            res236              null           sedres1           nutres1  
     237  res237                    initres1            res237              null           sedres1           nutres1  
     238  res238                    initres1            res238     drawdown_days           sedres1           nutres1  
     239  res239                    initres1            res239              null           sedres1           nutres1  
     240  res240                    initres1            res240              null           sedres1           nutres1  
     241  res241                    initres1            res241              null           sedres1           nutres1  
     242  res242                    initres1            res242              null           sedres1           nutres1  
     243  res243                    initres1            res243              null           sedres1           nutres1  
     244  res244                    initres1            res244              null           sedres1           nutres1  
     245  res245                    initres1            res245              null           sedres1           nutres1  
     246  res246                    initres1            res246              null           sedres1           nutres1  
     247  res247                    initres1            res247     drawdown_days           sedres1           nutres1  
     248  res248                    initres1            res248              null           sedres1           nutres1  
     249  res249                    initres1            res249              null           sedres1           nutres1  
     250  res250                    initres1            res250              null           sedres1           nutres1  
     251  res251                    initres1            res251              null           sedres1           nutres1  
     252  res252                    initres1            res252              null           sedres1           nutres1  
     253  res253                    initres1            res253              null           sedres1           nutres1  
     254  res254                    initres1            res254              null           sedres1           nutres1  
     255  res255                    initres1            res255     drawdown_days           sedres1           nutres1  
     256  res256                    initres1            res256              null           sedres1           nutres1  
     257  res257                    initres1            res257              null           sedres1           nutres1  
     258  res258                    initres1            res258              null           sedres1           nutres1  
